[build]
  functions = "netlify/functions"

# Route ALL paths to the function so the root domain works too.
# This forwards the original path to the Hono app unchanged.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
